### ISSUE TITLE
Implement An Endpoint For Creating A New Student Record.

### ISSUE THREAD

**Issue by Fourteen98** [Fourteen98/RegNow#3]
-  HTTP Method: POST
-  Endpoint: /api/v1 /students/
- Request Data: Student details (name, age, course, etc.).
- Validation: Validate the request data for correctness.
- Database: Store the student record in the SQLite database.
- Response: Return the newly created student's details.

**Comment by Fourteen98** [comment]
@Thenebit , base your proactiveness you can handle this!

**Comment by Thenebit** [comment]
Thanks for this task. Will jumpstart into it immediately
