### ISSUE TITLE
Create SQLAlchemy Programme Model Based on UI Mockup

### ISSUE THREAD

**Issue by Fourteen98** [Fourteen98/RegNow#9]
As part of the development for the student registration system API, we need to create SQLAlchemy models that align with the UI mock up and requirements. These models will serve as the foundation for storing student registration data.

### Programme Model:
- id: Integer, primary key, unique identifier.
- student: -> foreign to student model
- programme_name: tuple
- stream: tuple
- entry_level: tuple
- hall: tuple

### Model Validation:
- Ensure required fields are non-null and correctly validated.

### Database Migration:
- Generate a migration to create the students table.

**Comment by TURF777** [comment]
hi from the little i know concerning foreign to student model which is our `(index_number) can we identity it as`owner_id =Column(interger, ForeignKey("user.id"))` can we do that please ?????????????

**Comment by Fourteen98** [comment]
> hi from the little i know concerning foreign to student model which is our `(index_number) can we identity it as`owner_id =Column(interger, ForeignKey("user.id"))` can we do that please ?????????????

@TURF777, why owner_id, best will be student, if we had a model called owner we could have used that and here lies the case we dont have that.

**Comment by TURF777** [comment]
@Fourteen98 okay i get it now thanks

**Comment by TURF777** [comment]
@Fourteen98 THANKS

**Comment by 360konet** [comment]
from sqlalchemy import create_engine, Column, Integer, String, Date, ForeignKey
from sqlalchemy.orm import sessionmaker, relationship
from sqlalchemy.ext.declarative import declarative_base


engine = create_engine('sqlite:///program_database.db', echo=True)

Base = declarative_base()

class Program(Base):
    __tablename__ = 'programs'
    
    id = Column(Integer, primary_key=True)
    title = Column(String, nullable=False)
    description = Column(String)
    start_date = Column(Date)
    end_date = Column(Date)
    
    participants = relationship("Participant", back_populates="program")

class Participant(Base):
    __tablename__ = 'participants'
    
    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    program_id = Column(Integer, ForeignKey('programs.id'))
    
    program = relationship("Program", back_populates="participants")


Base.metadata.create_all(engine)


Session = sessionmaker(bind=engine)
session = Session()


new_program = Program(title="Sample Program", description="An example program", start_date="2023-09-01", end_date="2023-09-30")
participant1 = Participant(name="John Doe", program=new_program)
participant2 = Participant(name="Jane Smith", program=new_program)

session.add(new_program)
session.commit()


programs = session.query(Program).all()
for program in programs:
    print("Program:", program.title)
    print("Participants:")
    for participant in program.participants:
        print("-", participant.name)

session.close()

**Comment by Thenebit** [comment]
Use SQLModel instead of SQLAlchemy

**Comment by TURF777** [comment]
@Thenebit can you please demonstrate it to us?

**Comment by Thenebit** [comment]
so basically we want to use the SQLModel instead if the SQLAlchemy to create and define the table.
Sample:

from sqlmodel import Field, SQLModel
import uuid

class Programme(SQLModel, table=True):
__tablename__='programme'
id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
title: str
description: str
programme_id: str = Field(unique=True)

**Comment by Thenebit** [comment]
You can also check out this repo which i used SQLAlchemy
https://github.com/Thenebit/fast-api
